columns:
  Date: int
  Open: float
  High: float
  Low: float
  Close: float
  Last: float
  Volume: int

dataset_columns:
  - Date
  - Open
  - High
  - Low
  - Close
  - Volume

target_column: Last

stock_symbol: str
